SET search_path TO bd032_schema, public;


-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------

CREATE TABLE Unidade_Saude (
    id_unidade_saude INT          GENERATED BY DEFAULT AS IDENTITY,
    nome             VARCHAR(100) NOT NULL,
    morada           VARCHAR(100) NOT NULL,
    cidade           VARCHAR(50)  NOT NULL,
    pais             VARCHAR(50)  NOT NULL,
    telefone         VARCHAR(16)  NOT NULL,
    email            VARCHAR(100) NOT NULL,
    tipo_unidade     VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_Unidade_Saude PRIMARY KEY (id_unidade_saude),
    CONSTRAINT un_Unidade_Saude_telefone UNIQUE (telefone),
    CONSTRAINT ck_Unidade_Saude_telefone CHECK (telefone ~ '^\+?[0-9]{9,15}$'),
    CONSTRAINT un_Unidade_Saude_email UNIQUE (email),
    CONSTRAINT ck_Unidade_Saude_tipo_unidade CHECK (tipo_unidade IN ('Hospital', 'Clínica', 'Centro de Saúde'))
);

-- ---------------------------------------------------------------------------

CREATE TABLE Departamento (
    id_departamento INT          GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(100) NOT NULL,
    descricao       TEXT,
    CONSTRAINT pk_Departamento PRIMARY KEY (id_departamento)
);

-- ---------------------------------------------------------------------------

CREATE TABLE tem_unid_saude_dept (
    id_unidade_saude INT,
    id_departamento  INT,
    CONSTRAINT pk_tem_unid_saude_dept PRIMARY KEY (id_unidade_saude, id_departamento),
    CONSTRAINT fk_tem_unid_saude_dept_Unidade_Saude FOREIGN KEY (id_unidade_saude) REFERENCES Unidade_Saude (id_unidade_saude) ON DELETE CASCADE,
    CONSTRAINT fk_tem_unid_saude_dept_Departamento FOREIGN KEY (id_departamento) REFERENCES Departamento (id_departamento) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------

CREATE TABLE Profissional_Saude (
    id_profissional_saude INT          GENERATED BY DEFAULT AS IDENTITY,
    nome                  VARCHAR(100) NOT NULL,
    NIF                   VARCHAR(9)   NOT NULL,
    data_nascimento       DATE         NOT NULL,
    genero                CHAR(1)      NOT NULL,
    telefone              VARCHAR(16)  NOT NULL,
    email                 VARCHAR(100) NOT NULL,
    CONSTRAINT pk_Profissional_Saude PRIMARY KEY (id_profissional_saude),
    CONSTRAINT un_Profissional_Saude_NIF UNIQUE (NIF),
    CONSTRAINT ck_Profissional_Saude_NIF CHECK (NIF ~ '^[0-9]{9}$'),
    CONSTRAINT ck_Profissional_Saude_genero CHECK (genero IN ('F', 'M')),
    CONSTRAINT un_Profissional_Saude_telefone UNIQUE (telefone),
    CONSTRAINT ck_Profissional_Saude_telefone CHECK (telefone ~ '^\+?[0-9]{9,15}$'),
    CONSTRAINT un_Profissional_Saude_email UNIQUE (email)
);

-- ---------------------------------------------------------------------------

CREATE TABLE pertence_dept_prof_saude (
    id_departamento       INT,
    id_profissional_saude INT,
    CONSTRAINT pk_pertence_dept_prof_saude PRIMARY KEY (id_departamento, id_profissional_saude),
    CONSTRAINT fk_pertence_dept_prof_saude_Departamento FOREIGN KEY (id_departamento) REFERENCES Departamento (id_departamento) ON DELETE CASCADE,
    CONSTRAINT fk_pertence_dept_prof_saude_Profissional_Saude FOREIGN KEY (id_profissional_saude) REFERENCES Profissional_Saude (id_profissional_saude) ON DELETE CASCADE,
    CONSTRAINT un_pertence_dept_prof_saude_id_profissional_saude UNIQUE (id_profissional_saude)
);

-- ---------------------------------------------------------------------------

CREATE TABLE Medico (
    id_profissional_saude     INT,
    numero_ordem_profissional VARCHAR(20)  NOT NULL,
    especialidade             VARCHAR(100),
    anos_experiencia          SMALLINT,
    CONSTRAINT pk_Medico PRIMARY KEY (id_profissional_saude),
    CONSTRAINT fk_Medico_Profissional_Saude FOREIGN KEY (id_profissional_saude) REFERENCES Profissional_Saude (id_profissional_saude) ON DELETE CASCADE,
    CONSTRAINT un_Medico_numero_ordem_profissional UNIQUE (numero_ordem_profissional),
    CONSTRAINT ck_Medico_anos_experiencia CHECK (anos_experiencia >= 0)
);

-- ---------------------------------------------------------------------------

CREATE TABLE Enfermeiro (
    id_profissional_saude     INT,
    numero_ordem_profissional VARCHAR(20)  NOT NULL,
    especialidade             VARCHAR(100),
    anos_experiencia          SMALLINT,
    CONSTRAINT pk_Enfermeiro PRIMARY KEY (id_profissional_saude),
    CONSTRAINT fk_Enfermeiro_Profissional_Saude FOREIGN KEY (id_profissional_saude) REFERENCES Profissional_Saude (id_profissional_saude) ON DELETE CASCADE,
    CONSTRAINT un_Enfermeiro_numero_ordem_profissional UNIQUE (numero_ordem_profissional),
    CONSTRAINT ck_Enfermeiro_anos_experiencia CHECK (anos_experiencia >= 0)
);

-- ---------------------------------------------------------------------------

-- TABELA DE TÉCNICO!? TEMOS DE DECIDIR SE MANTEMOS OU NÃO..

-- ---------------------------------------------------------------------------

CREATE TABLE Consulta (
    id_consulta   INT         GENERATED BY DEFAULT AS IDENTITY,
    data_hora     TIMESTAMP   NOT NULL,
    tipo_consulta VARCHAR(20) NOT NULL,
    estado        VARCHAR(20) NOT NULL,
    motivo        TEXT        NOT NULL,
    diagnostico   TEXT,
    observacoes   TEXT,
    CONSTRAINT pk_Consulta PRIMARY KEY (id_consulta),
    CONSTRAINT ck_Consulta_tipo_consulta CHECK (tipo_consulta IN ('Primeira', 'Urgência', 'Rotina')), -- Depois podemos adicionar mais ou tirar esta restrição
    CONSTRAINT ck_Consulta_estado CHECK (estado IN ('Marcada', 'Realizada', 'Cancelada'))
);

-- ---------------------------------------------------------------------------

CREATE TABLE realiza_med_cons (
    id_profissional_saude INT,
    id_consulta           INT,
    CONSTRAINT pk_realiza_med_cons PRIMARY KEY (id_profissional_saude, id_consulta),
    CONSTRAINT fk_realiza_med_cons_Medico FOREIGN KEY (id_profissional_saude) REFERENCES Medico (id_profissional_saude) ON DELETE CASCADE,
    CONSTRAINT fk_realiza_med_cons_Consulta FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta) ON DELETE CASCADE,
    CONSTRAINT un_realiza_med_cons_id_consulta UNIQUE (id_consulta)
);

-- ---------------------------------------------------------------------------

CREATE TABLE participa_enf_cons (
    id_profissional_saude INT,
    id_consulta           INT,
    CONSTRAINT pk_participa_enf_cons PRIMARY KEY (id_profissional_saude, id_consulta),
    CONSTRAINT fk_participa_enf_cons_Enfermeiro FOREIGN KEY (id_profissional_saude) REFERENCES Enfermeiro (id_profissional_saude) ON DELETE CASCADE,
    CONSTRAINT fk_participa_enf_cons_Consulta FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------

CREATE TABLE Paciente (
    id_paciente         INT          GENERATED BY DEFAULT AS IDENTITY,
    nome                VARCHAR(100) NOT NULL,
    NIF                 VARCHAR(9)   NOT NULL,
    numero_utente       VARCHAR(9)   NOT NULL,
    data_nascimento     DATE         NOT NULL,
    genero              CHAR(1)      NOT NULL,
    morada              VARCHAR(100) NOT NULL,
    telefone            VARCHAR(16)  NOT NULL,
    contacto_emergencia VARCHAR(16)  NOT NULL,
    email               VARCHAR(100) NOT NULL,
    CONSTRAINT pk_Paciente PRIMARY KEY (id_paciente),
    CONSTRAINT un_Paciente_NIF UNIQUE (NIF),
    CONSTRAINT ck_Paciente_NIF CHECK (NIF ~ '^[0-9]{9}$'),
    CONSTRAINT un_Paciente_numero_utente UNIQUE (numero_utente),
    CONSTRAINT ck_Paciente_numero_utente CHECK (numero_utente ~ '^[0-9]{9}$'),
    CONSTRAINT ck_Paciente_genero CHECK (genero IN ('F', 'M')),
    CONSTRAINT un_Paciente_telefone UNIQUE (telefone),
    CONSTRAINT ck_Paciente_telefone CHECK (telefone ~ '^\+?[0-9]{9,15}$'),
    CONSTRAINT ck_Paciente_contacto_emergencia CHECK (contacto_emergencia ~ '^\+?[0-9]{9,15}$'), -- Não meti UNIQUE porque uma pessoa pode ser o contacto de emergência de várias
    CONSTRAINT ck_Paciente_telefone_contacto_emergencia CHECK (telefone <> contacto_emergencia), -- Para garantir que o contacto de emergência é diferente do telefone da pessoa
    CONSTRAINT un_Paciente_email UNIQUE (email)
);

-- ---------------------------------------------------------------------------

CREATE TABLE tem_cons_paci (
    id_consulta INT,
    id_paciente INT,
    CONSTRAINT pk_tem_cons_paci PRIMARY KEY (id_consulta, id_paciente),
    CONSTRAINT fk_tem_cons_paci_Consulta FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta) ON DELETE CASCADE,
    CONSTRAINT fk_tem_cons_paci_Paciente FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente) ON DELETE CASCADE,
    CONSTRAINT un_tem_cons_paci_id_consulta UNIQUE (id_consulta)
);

-- ---------------------------------------------------------------------------

CREATE TABLE Historico_Medico (
    id_historico_medico INT          GENERATED BY DEFAULT AS IDENTITY,
    data_registo        DATE         NOT NULL,
    condicao            VARCHAR(100) NOT NULL,
    descricao           TEXT,
    CONSTRAINT pk_Historico_Medico PRIMARY KEY (id_historico_medico)
);

-- ---------------------------------------------------------------------------

CREATE TABLE possui_paci_hist_med (
    id_paciente         INT,
    id_historico_medico INT,
    CONSTRAINT pk_possui_paci_hist_med PRIMARY KEY (id_paciente, id_historico_medico),
    CONSTRAINT fk_possui_paci_hist_med_Paciente FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente) ON DELETE CASCADE,
    CONSTRAINT fk_possui_paci_hist_med_Historico_Medico FOREIGN KEY (id_historico_medico) REFERENCES Historico_Medico (id_historico_medico) ON DELETE CASCADE,
    CONSTRAINT un_possui_paci_hist_med_id_historico_medico UNIQUE (id_historico_medico)
);

-- ---------------------------------------------------------------------------

CREATE TABLE Prescricao (
    id_consulta   INT,
    id_prescricao INT  GENERATED BY DEFAULT AS IDENTITY,
    data_emissao  DATE NOT NULL,
    descricao     TEXT,
    CONSTRAINT pk_Prescricao PRIMARY KEY (id_consulta, id_prescricao),
    CONSTRAINT fk_Prescricao_Consulta FOREIGN KEY (id_consulta) REFERENCES Consulta (id_consulta) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------

CREATE TABLE Medicamento (
    id_medicamento     INT          GENERATED BY DEFAULT AS IDENTITY,
    nome               VARCHAR(100) NOT NULL,
    substancia_ativa   VARCHAR(50)  NOT NULL,
    dosagem            VARCHAR(50)  NOT NULL,
    forma_farmaceutica VARCHAR(50)  NOT NULL,
    quantidade_stock   INT          NOT NULL,
    nivel_min_stock    INT          NOT NULL,
    data_validade      DATE         NOT NULL,
    categoria          VARCHAR(50)  NOT NULL,
    fornecedor         VARCHAR(100),
    CONSTRAINT pk_Medicamento PRIMARY KEY (id_medicamento),
    CONSTRAINT un_Medicamento_nome_substancia_ativa_dosagem_forma_farmaceutica UNIQUE (nome, substancia_ativa, dosagem, forma_farmaceutica),
    CONSTRAINT ck_Medicamento_quantidade_stock CHECK (quantidade_stock >= 0),
    CONSTRAINT ck_Medicamento_nivel_min_stock CHECK (nivel_min_stock >= 0)
);

-- ---------------------------------------------------------------------------

CREATE TABLE contem_presc_medi (
    id_consulta    INT,
    id_prescricao  INT,
    id_medicamento INT,
    CONSTRAINT pk_contem_presc_medi PRIMARY KEY (id_consulta, id_prescricao, id_medicamento),
    CONSTRAINT fk_contem_presc_medi_Prescricao FOREIGN KEY (id_consulta, id_prescricao) REFERENCES Prescricao (id_consulta, id_prescricao) ON DELETE CASCADE,
    CONSTRAINT fk_contem_presc_medi_Medicamento FOREIGN KEY (id_medicamento) REFERENCES Medicamento (id_medicamento) ON DELETE CASCADE
);

-- TRIGGER 1 Medicamento por Prescrição

-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION alerta_stock_abaixo_nivel_min() -- TRIGGER quantidade_stock < nivel_min_stock
RETURNS TRIGGER
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.quantidade_stock < NEW.nivel_min_stock THEN
            RAISE NOTICE
                'ALERTA! Stock abaixo do nível mínimo para o medicamento % (stock = % < min = %).',
                NEW.id_medicamento, NEW.quantidade_stock, NEW.nivel_min_stock;
        END IF;
    ELSIF TG_OP = 'UPDATE' THEN
        IF (COALESCE(OLD.quantidade_stock >= OLD.nivel_min_stock, TRUE))
           AND (NEW.quantidade_stock < NEW.nivel_min_stock) THEN
            RAISE NOTICE
                'ALERTA! Stock abaixo do nível mínimo para o medicamento % (stock = % < min = %).',
                NEW.id_medicamento, NEW.quantidade_stock, NEW.nivel_min_stock;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER alerta_stock_abaixo_nivel_min_trigger
AFTER INSERT OR UPDATE OF quantidade_stock, nivel_min_stock
ON Medicamento
FOR EACH ROW
EXECUTE FUNCTION alerta_stock_abaixo_nivel_min();

-- ---------------------------------------------------------------------------

